# Use the official .NET SDK as the build environment
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

# Set the working directory in the container
WORKDIR /app

# Copy the .csproj and .sln files to the container
COPY *.sln ./
COPY ECommerceWeb/*.csproj ./ECommerceWeb/
COPY ECommerceAdmin/*.csproj ./ECommerceAdmin/

# Restore NuGet packages
RUN dotnet restore

# Copy the remaining source code to the container
COPY . ./

# Build the application
RUN dotnet publish -c Release -o out

# Build the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

# Expose the port that your application listens on (adjust as needed)
EXPOSE 80

# Define the command to start your application
ENTRYPOINT ["dotnet", "ECommerceWeb.dll"]
